/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as SellTicketsRouteImport } from './routes/sell-tickets'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CitiesRouteImport } from './routes/cities'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as OrganizerRegisterRouteImport } from './routes/organizer.register'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as DashboardFormRouteImport } from './routes/dashboard.form'
import { Route as CheckoutStatusRouteImport } from './routes/checkout.status'
import { Route as CheckoutEventIdRouteImport } from './routes/checkout.$eventId'
import { Route as AdminLoginRouteImport } from './routes/admin_.login'

const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const SellTicketsRoute = SellTicketsRouteImport.update({
  id: '/sell-tickets',
  path: '/sell-tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesRoute = CitiesRouteImport.update({
  id: '/cities',
  path: '/cities',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerRegisterRoute = OrganizerRegisterRouteImport.update({
  id: '/organizer/register',
  path: '/organizer/register',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardFormRoute = DashboardFormRouteImport.update({
  id: '/dashboard/form',
  path: '/dashboard/form',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutStatusRoute = CheckoutStatusRouteImport.update({
  id: '/checkout/status',
  path: '/checkout/status',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutEventIdRoute = CheckoutEventIdRouteImport.update({
  id: '/checkout/$eventId',
  path: '/checkout/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin_/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/browse': typeof BrowseRoute
  '/categories': typeof CategoriesRoute
  '/cities': typeof CitiesRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/scan': typeof ScanRoute
  '/sell-tickets': typeof SellTicketsRoute
  '/tickets': typeof TicketsRoute
  '/admin/login': typeof AdminLoginRoute
  '/checkout/$eventId': typeof CheckoutEventIdRoute
  '/checkout/status': typeof CheckoutStatusRoute
  '/dashboard/form': typeof DashboardFormRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/organizer/register': typeof OrganizerRegisterRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/browse': typeof BrowseRoute
  '/categories': typeof CategoriesRoute
  '/cities': typeof CitiesRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/scan': typeof ScanRoute
  '/sell-tickets': typeof SellTicketsRoute
  '/tickets': typeof TicketsRoute
  '/admin/login': typeof AdminLoginRoute
  '/checkout/$eventId': typeof CheckoutEventIdRoute
  '/checkout/status': typeof CheckoutStatusRoute
  '/dashboard/form': typeof DashboardFormRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/organizer/register': typeof OrganizerRegisterRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/browse': typeof BrowseRoute
  '/categories': typeof CategoriesRoute
  '/cities': typeof CitiesRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/scan': typeof ScanRoute
  '/sell-tickets': typeof SellTicketsRoute
  '/tickets': typeof TicketsRoute
  '/admin_/login': typeof AdminLoginRoute
  '/checkout/$eventId': typeof CheckoutEventIdRoute
  '/checkout/status': typeof CheckoutStatusRoute
  '/dashboard/form': typeof DashboardFormRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/organizer/register': typeof OrganizerRegisterRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/browse'
    | '/categories'
    | '/cities'
    | '/contact'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/resources'
    | '/scan'
    | '/sell-tickets'
    | '/tickets'
    | '/admin/login'
    | '/checkout/$eventId'
    | '/checkout/status'
    | '/dashboard/form'
    | '/events/$eventId'
    | '/organizer/register'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/browse'
    | '/categories'
    | '/cities'
    | '/contact'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/resources'
    | '/scan'
    | '/sell-tickets'
    | '/tickets'
    | '/admin/login'
    | '/checkout/$eventId'
    | '/checkout/status'
    | '/dashboard/form'
    | '/events/$eventId'
    | '/organizer/register'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/browse'
    | '/categories'
    | '/cities'
    | '/contact'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/resources'
    | '/scan'
    | '/sell-tickets'
    | '/tickets'
    | '/admin_/login'
    | '/checkout/$eventId'
    | '/checkout/status'
    | '/dashboard/form'
    | '/events/$eventId'
    | '/organizer/register'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  BrowseRoute: typeof BrowseRoute
  CategoriesRoute: typeof CategoriesRoute
  CitiesRoute: typeof CitiesRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResourcesRoute: typeof ResourcesRoute
  ScanRoute: typeof ScanRoute
  SellTicketsRoute: typeof SellTicketsRoute
  TicketsRoute: typeof TicketsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  CheckoutEventIdRoute: typeof CheckoutEventIdRoute
  CheckoutStatusRoute: typeof CheckoutStatusRoute
  DashboardFormRoute: typeof DashboardFormRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  OrganizerRegisterRoute: typeof OrganizerRegisterRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell-tickets': {
      id: '/sell-tickets'
      path: '/sell-tickets'
      fullPath: '/sell-tickets'
      preLoaderRoute: typeof SellTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities': {
      id: '/cities'
      path: '/cities'
      fullPath: '/cities'
      preLoaderRoute: typeof CitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/register': {
      id: '/organizer/register'
      path: '/organizer/register'
      fullPath: '/organizer/register'
      preLoaderRoute: typeof OrganizerRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/form': {
      id: '/dashboard/form'
      path: '/dashboard/form'
      fullPath: '/dashboard/form'
      preLoaderRoute: typeof DashboardFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/status': {
      id: '/checkout/status'
      path: '/checkout/status'
      fullPath: '/checkout/status'
      preLoaderRoute: typeof CheckoutStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$eventId': {
      id: '/checkout/$eventId'
      path: '/checkout/$eventId'
      fullPath: '/checkout/$eventId'
      preLoaderRoute: typeof CheckoutEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/login': {
      id: '/admin_/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  BrowseRoute: BrowseRoute,
  CategoriesRoute: CategoriesRoute,
  CitiesRoute: CitiesRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResourcesRoute: ResourcesRoute,
  ScanRoute: ScanRoute,
  SellTicketsRoute: SellTicketsRoute,
  TicketsRoute: TicketsRoute,
  AdminLoginRoute: AdminLoginRoute,
  CheckoutEventIdRoute: CheckoutEventIdRoute,
  CheckoutStatusRoute: CheckoutStatusRoute,
  DashboardFormRoute: DashboardFormRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  OrganizerRegisterRoute: OrganizerRegisterRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
